### ISSUE TITLE
Add virtual method to QtnPropertySet

### ISSUE THREAD

**Issue by wertas** [qtinuum/QtnProperty#40]
Hello. Working with QtnPropertySetXXX i created own method QtnPropertySetXXX::method() in pef file. I need to operate it from base class.
If topic name solution isnt suitable, how could it be achieved without casting?

**Comment by lexxmark** [comment]
Sorry for long delay,

I do not quite understand a problem statement.
 Please give an example of what do you want to achieve? How you want to achieve it if your class derived for example from QWidget class?

**Comment by lexxmark** [comment]
Let's reopen it if it's still relevant
