### ISSUE TITLE
when use QObjectPropertyWidget show object property, then drag splitter crash

### ISSUE THREAD

**Issue by Caprey** [qtinuum/QtnProperty#45]
![T2](https://user-images.githubusercontent.com/28674556/101887332-af4d0580-3bd7-11eb-9a11-39aebbfa0d8d.gif)

**Comment by lexxmark** [comment]
fixed in `develop` branch, please verify.

**Comment by kusharami** [comment]
fixed splitter break with drag action in QtnPropertyWidgetEx and QObjectPropertyWidget that was used in gif, and also fixed compilation in older compilers (std::make_unique is c++14 feature)

**Comment by kusharami** [comment]
merged to master with v2.0.2 release
