### ISSUE TITLE
Inplace editing must start by both Key_Return and Key_Enter

### ISSUE THREAD

**Issue by niello** [qtinuum/QtnProperty#48]
QtnPropertyDelegateWithValueEditor::acceptKeyPressedForInplaceEditImpl

**Comment by lexxmark** [comment]
@niello Do you have a pull request for this improvement?

**Comment by niello** [comment]
Not yet. I just wrote it down not to forget)

**Comment by lexxmark** [comment]
Does this pull request https://github.com/qtinuum/QtnProperty/pull/49 do that you need?

**Comment by niello** [comment]
Yes, thank you, looks exactly like what I need

**Comment by niello** [comment]
Closed by #49
