### ISSUE TITLE
Use existing delegate for custom data type

### ISSUE THREAD

**Issue by niello** [qtinuum/QtnProperty#51]
I have some custom types which closely resemble Qt types with property delegates already implemented. E.g. Colour -> QColor, glm::vec2 -> QPointF. I would like to reuse existing delegates and write as little bridge code as possible. In a perfect case there would be only two methods to convert between these types back and forth. What is the easiest way to reuse delegates right now? Are some improvements possible?

**Comment by niello** [comment]
@lexxmark, will it work with multiproperty?

**Comment by lexxmark** [comment]
I'm not familiar with multiproperty. As it inherits OldValueType base property so I don't see any issues there. Try it.
